### ISSUE TITLE
Menu bug on Android devices

### ISSUE THREAD

**Issue by paulcredmond** [mrjasonweaver/flexnav#54]
I'm doing some testing with Flexnav and seem to have come across a bug on a lot of Android devices. Granted, I'm testing them using Browserstack as I don't have access to an Android device so I may be wrong about this. It seems when you click the menu item the menu drops down and then immediately disappears/collapses again. Tested on a GS2 and GS3 with the stock browser. Can anyone duplicate this potential bug?

**Comment by ghost** [comment]
I tested a bit earlier (with the default browser) on a device with Android 2.3.6 and the problem wasn't present. Maybe someone else will help with a newer device.

**Comment by mrjasonweaver** [comment]
Looking into this.

**Comment by NRobotham** [comment]
I tested flexnav on 2.3.3 (using eclipse) and on Android devices with 2.3.5, 4.1.1 and 4.1.2. I can confirm they all show the bug described by paulcredmond, except for 2.3.5 which doesn't open the menu at all.

The menu drops down and then immediately collapses again, but if you touch and hold down for a second the menu will drop down and stay open.

I really like flexnav and want to use it for a project so it would be much appreciated if you could fix this bug.

Hope this is of any use.

**Comment by mrjasonweaver** [comment]
Thanks @NRobotham! Looking into this. I've got a major release coming that should fix this issue.

**Comment by NRobotham** [comment]
Thanks for your quick reply! Looking forward to the new release.
Op 30 jul. 2013 18:13 schreef "Jason Weaver" notifications@github.com het
volgende:

**Comment by mrjasonweaver** [comment]
Doing some browser testing for the new v1.0 release: https://github.com/indyplanets/flexnav/pull/56 ([test demo here](http://jasonweaver.name/lab/flexiblenavigation-test/)).

All Android browsers for smartphones seem to be working fine now but I'm running into issues with larger touch screens (tablets) where the drop downs are showing for just a second and then retracting back up. Looking into fixing this issue this weekend.

**Comment by mrjasonweaver** [comment]
Tested on Android devices and couldn't replicate this bug anymore. Closing for now but please comment here if anyone finds an issue.

**Comment by NRobotham** [comment]
I downloaded and tested the latest version but still having the dropdown/retracting bug!

I'm using Android 4.1.1 on a galaxy tab 2 and Android 4.1.2 on a XPeria S mobile phone. When tapping on the edge (which looks like tapping outside the menu button) the menu does drop down as it should. But just tapping in the middle as you would normally do shows the bug again. The touchbuttons for the submenu items are also still showing the bug. 

Is the provided test demo link posted before up to date? I also tested with this link but also still shows the bug.
....or am I just doing something wrong?

**Comment by mrjasonweaver** [comment]
@NRobotham  Hmm, Let me do more testing then. http://jasonweaver.name/lab/flexiblenavigation is up to date. I'm going to grab a galaxy tab 2 and test it out. Are you testing on the default browser?

**Comment by NRobotham** [comment]
Yes, testing on the default browser. It works fine on other browsers like FF, Chrome, Opera.

**Comment by mrjasonweaver** [comment]
I've released v1.1. https://github.com/indyplanets/flexnav/releases/tag/v1.1

This adds timeout flags to events that attempt to stop double firing on some Android browsers. I couldn't replicate the bug so post here if your issues stopped or still persist. Thanks!

**Comment by NRobotham** [comment]
Jason, I've tested the new release (1.1) and http://jasonweaver.name/lab/flexiblenavigation again. I'm sorry to say that the dropdown/retracting bug still persists on the default android browsers (android 4.1.1 and 4.1.2).

Were you able to test on a galaxy tab 2?

Hope I'm not getting on your nerves

Niels

**Comment by mrjasonweaver** [comment]
@NRobotham Ok. I wasn't able to reproduce it on a galaxy tab 3. I'll go find a 2 to test on.

**Comment by mrjasonweaver** [comment]
@NRobotham Can you jump on a Skype call for testing? I'm mrJasonWeaver on Skype.

**Comment by ghost** [comment]
@indyplanets I feel pretty sorry right now that I don't have more Android devices to test with and help you guys. Anyway, sending both of you big, grizzly bear hugs, encouragements for your work + loads of virtual beer :+1:

**Comment by mrjasonweaver** [comment]
@pallandt Thanks! We'll get this pesky bug figured out. I have a few ideas and may have to take away features in order to solve this. I'd rather have the nav accessible on all devices and if that means taking away fast clicks then I'm cool with that. :beer: :rocket: :octocat:

**Comment by ghost** [comment]
@indyplanets You probably know about this library, but in case not, and if you'll have to remove fast click support from your project, perhaps add a suggestion in the readme for this https://github.com/ftlabs/fastclick as a potential 'add-on' for the people that need this behavior. More at http://labs.ft.com/articles/ft-fastclick/

**Comment by mrjasonweaver** [comment]
@pallandt Yes. Thanks. I was considering that.

**Comment by NRobotham** [comment]
@indyplanets I would be more then happy to help you if you want me to test a couple things... it's the least I can do. So a Skype call is a good idea. I've noticed a time difference of 7 hours between Texas and the Netherlands so I'm not sure when to call. I might be able to skype Friday afternoon (around 11.00 - 12.00 Texas time?) but not sure....so it will probably be Saturday (afternoon). Is that ok? Or should I just try and call when your online?

I think I'm able to test your demo page on more android devices on Friday. I'll get back to you on that. Grtz.

**Comment by mrjasonweaver** [comment]
@NRobotham Saturday works for me. Ping me on the Skypes.

**Comment by Kinky69** [comment]
Hi Jason,
i can confirm this bug. Testet on various Android Tablets - Samsung Galaxy 3 (7.0),Samsung Galaxy 3 (8.0)) and another no Name-Tablet (Android 4.2). With version 0.9 this bug does not appear. Greets

**Comment by howlermonkey** [comment]
Is there any update on this bug?

**Comment by mrjasonweaver** [comment]
I've removed touchstart event handlers to see if this is causing the issue. https://github.com/indyplanets/flexnav/releases/tag/v1.2 Cannot reproduce this bug. Can I get some testers? http://jasonweaver.name/lab/flexiblenavigation

**Comment by mrjasonweaver** [comment]
After testing on a few Android devices I've decided to close this issue. I'll reopen if someone can reproduce.

**Comment by howlermonkey** [comment]
Hi Jason,

Can you check
www.aestheticlaserclinic.co.uk on Android? I have updated your script, but
still having issues.

THanks again.

Iain Howell
t: 07984925526
e: iain@howlermonkey.co.uk

https://plus.google.com/u/0/102794957248369584889/
http://www.twitter.com/iainhowell
   http://www.dribbble.com/howlermonkey
http://www.stumbleupon.com/stumbler/ihowell/
 http://www.stumbleupon.com/stumbler/ihowell/

**Comment by ghost** [comment]
@howlermonkey  I've checked your Joomla site in the W3C validator, there are 2 clear errors caused by missing closing tags somewhere and quite a handful of warnings. It is possible that the issues you're experiencing are related to this and not to flexnav.
The definitive confirmation would be to just check the official demo for flexnav on the same Android device + browser you used to access the site you mentioned. If you get the same issue(s) with the original demo, please post back the device type, as well as exact Android version; also specify if you used the default browser or if not, what specific browser was used.

**Comment by howlermonkey** [comment]
I have resolved it..
It was due to the jquery version needing to be a recent version. I have it
working with 1.10.2.

Is it worth including the jquery version in github zip or specified on your
site.

Thanks again for all your help..
PS. looking into the errors now too..

Iain Howell
t: 07984925526
e: iain@howlermonkey.co.uk

https://plus.google.com/u/0/102794957248369584889/
http://www.twitter.com/iainhowell
   http://www.dribbble.com/howlermonkey
http://www.stumbleupon.com/stumbler/ihowell/
 http://www.stumbleupon.com/stumbler/ihowell/

**Comment by NRobotham** [comment]
@indyplanets I tested v1.2 

The menu drops down and immediately collapses again... but this only happens if you click the menu item for the first time and only at the given breakpoint when the full menu is showing. The second time (click) it works as expected.

Hope this is minor issue.

**Comment by prowebdesignro** [comment]
I can confirm what @indyplanets said. Tested on Samsung Galaxy Note 10.1

**Comment by delime** [comment]
Hello, i've got the some bug as @indyplanets. Android 4.4.2 Nexus 10
